### ISSUE TITLE
不知道为啥可以水平垂直地方法子。。。0.0

### ISSUE THREAD

**Issue by mlyknown** [Erichain/css-center-complete#1]
.divtcvm{
    position: absolute; left: 0; top: 0; right: 0; bottom: 0; margin: auto;
}

**Comment by Erichain** [comment]
@mlyknown 这个方法确实可以居中。主要就是设置上下左右为0，以及`margin: auto;`

至于原理嘛，我也不是很清楚。可以看看这篇文章：
http://www.zhangxinxu.com/wordpress/2013/11/margin-auto-absolute-绝对定位-水平垂直居中/

**Comment by mlyknown** [comment]
川姐牛逼 0.0   求带求带~~
